export default {
  ACCESS_TOKEN: "@access_token",
  REFRESH_TOKEN: "@refresh_token",
  IS_LOGGED_IN: "@is_logged_in",
  USER_DETAILS_JSON: "@user_details_json",
  FULL_LOGIN_DETAILS_JSON: "@full_login_details_json",
  USERNAME: "@username",
  SHOP_ID: "@shop_id",
  SHOP_COUNT: "@shop_count",
  LOGIN_TIME: "@login_time",
  SHOPS: "@shops",
  SHOP_PRODUCTS: "@shop_products",
  PENDING_SALES: "@pending_sales",
  PIN_CODE: "@pincode",
  PIN_LOGIN: "@pin_login",
  SHOP_CLIENTS: "@shop_clients",
  LOGIN_DETAILS: "@login_details",
};
