export const LOGIN_ACTION = "LOGIN";
export const REFRESH_TOKEN = "REFRESH_TOKEN";

export const LOG_OUT = "LOG_OUT";
export const CHANGE_USER = "CHANGE_USER";
export const CHANGE_USER_TYPE = "CHANGE_USER_TYPE";
export const SET_APPLOCK_TIME = "SET_APPLOCK_TIME";
export const SET_IS_USER_CONFIGURED = "SET_IS_USER_CONFIGURED";
export const CHANGE_SELECTED_SHOP = "CHANGE_SELECTED_SHOP";
export const SET_SHOPS = "SET_SHOPS";
export const SET_USER_PIN_CODE = "SET_USER_PIN_CODE";

//cart

export const SET_SHOP_PRODUCTS = "SET_SHOP_PRODUCTS";

export const ADD_OFFLINE_SALE = "ADD_OFFLINE_SALE";
export const REMOVE_OFFLINE_SALE = "REMOVE_OFFLINE_SALE";

export const ADD_SHOP_CLIENTS = "ADD_SHOP_CLIENTS";

export const ADD_CLIENT_SALES = "ADD_CLIENT_SALES";

export const ADD_TO_CART = "ADD_TO_CART";

export const EDIT_CART_ITEM = "EDIT_CART_ITEM";

export const MAKE_PRODUCT_SELECTION = "MAKE_PRODUCT_SELECTION";
export const CHANGE_sELECTION_SALE_UNIT = "CHANGE_sELECTION_SALE_UNIT";

export const OFFERS_DEBT = "OFFERS_DEBT";

export const COLLECT_CLIENTS_INFO = "COLLECT_CLIENTS_INFO";

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_RECIEVED_AMOUNT = "UPDATE_RECIEVED_AMOUNT";
export const INCREMENT_ITEM_COUNT = "INCREMENT_ITEM_COUNT";
export const DECREMENT_ITEM_COUNT = "DECREMENT_ITEM_COUNT";

export const ADD_MANUFACTURERS = "ADD_MANUFACTURERS";
export const ADD_SUPPLIERS = "ADD_SUPPLIERS";
export const ADD_HELD_TXN = "ADD_HELD_TXN";

export const ADD_HELD_TXNS_TO_CART = "ADD_HELD_TXNS_TO_CART";

export const REMOVE_HELD_TXN = "REMOVE_HELD_TXN";

export const ADD_LOOK_UPS = "ADD_LOOK_UPS";
export const CLEAR_STATE = "CLEAR_STATE";
