export const LOGIN_ACTION = "LOGIN";

export const CHANGE_USER = "CHANGE_USER";
export const CHANGE_USER_TYPE = "CHANGE_USER_TYPE";

export const CHANGE_SELECTED_SHOP = "CHANGE_SELECTED_SHOP";
export const SET_SHOPS = "SET_SHOPS";

//cart
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const INCREMENT_ITEM_COUNT = "INCREMENT_ITEM_COUNT";
export const DECREMENT_ITEM_COUNT = "DECREMENT_ITEM_COUNT";
